eureka:
  client:
    service-url:
      # 注册中心地址 向Eureka注册
      # Eureka如果是集群的话，注册到Eureka集群使用“,”分割
      # defaultZone: http://localhost:8761/eureka/，http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
    # 注册到Eureka Status自定义名称
  instance:
    instance-id: spring-cloud-config-server-3344
    # 注册到Eureka Status自定义IP
    prefer-ip-address: true
# client 应用名称
spring:
  application:
    name: spring-cloud-config-server
    # Github远程仓库地址
  cloud:
    config:
      server:
        git:
          uri: git@github.com:xr2117/Spring-Cloud-Yml.git
  # bus 配置rabbitmq
  rabbitmq:
    host: 106.13.66.245
    port: 5672
    username: guest
    password: guest
#  暴露接口 http://localhost:3344/actuator/bus-refresh 刷新配置，cloud默认关闭改接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
#tomcat端口
server:
  port: 3344