eureka:
  client:
    service-url:
      # 注册中心地址 向Eureka注册
      # Eureka如果是集群的话，注册到Eureka集群使用“,”分割
      # defaultZone: http://localhost:8761/eureka/，http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
    # 注册到Eureka Status自定义名称 hystrix表示该服务带熔断
  instance:
    instance-id: spring-cloud-zuul-9527
    # 注册到Eureka Status自定义IP
    prefer-ip-address: true
# client 应用名称
spring:
  application:
    name: spring-cloud-zuul
#tomcat端口
server:
  port: 9527

zuul:
  # 可以设置公共前缀（可选）
  prefix: /crazy
  # 隐藏 原服务地址  http://localhost:9527/spring-cloud-provider/zuul
  # 单独或多个地址以 ， 分割  ignored-services:  spring-cloud-provider,spring-cloud-consumer
  # "*" 所有 通配符
  ignored-services:  "*"
  # 路由映射
  routes:
    # provider. 自定义的
    provider.serviceId: spring-cloud-provider
    provider.path: /provider/**
    consumer.serviceId: spring-cloud-consumer
    consumer.path: /consumer/**